#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean moleFractions
wclean laminarTransport
wclean radiationModels
wclean chemistryModel

# ----------------------------------------------------------------- end-of-file
